timeline
  title Evolución de las Bases de Datos
  section Primeros Desarrollos
    1884 : Herman Hollerith desarrolla el tabulador electromagnético
  section Primeros Sistemas de Gestión
    1950s-1960s : Surgen los primeros sistemas de gestión de datos
    1963 : Se utiliza por primera vez el término "base de datos"
  section Modelo Relacional
    1970 : Edgar F. Codd propone el modelo relacional
    1970s : IBM desarrolla System R
    1976 : Introducción del modelo entidad-relación (ER)
  section Lenguajes y DBMS
    1980 : Desarrollo del lenguaje SQL
    1980s : Surgen DBMS como Oracle y DB2
  section Nuevas Tecnologías
    1990 : Microsoft lanza Access y Excel
    1993 : La World Wide Web se hace pública
    1998 : Emergen bases de datos NoSQL
    2000 : Introducción de bases de datos de series temporales
    2000 : Introducción de bases de datos de grafos
  section Bases de Datos Modernas
    2005 : Desarrollo de bases de datos en memoria (In-Memory)
    2006 : Surge Hadoop como un marco distribuido de almacenamiento y procesamiento de datos
    2008 : Popularización de MySQL
    2008 : Introducción de bases de datos Blockchain
    2009 : Emergen bases de datos columnar
    2010 : Emergen sistemas de bases de datos XML
    2010s : Aparición de bases de datos basadas en la nube
    2013 : Surge el concepto de bases de datos NewSQL
  section Innovaciones Recientes
    2018 - Actualidad : Integración de IA y big data
    2020s : Integración de IA Generativa y aprendizaje automático en bases de datos